### ISSUE TITLE
ModuleNotFoundError: No module named 'ui.linbox_rc'

### ISSUE THREAD

**Issue by sunmin89** [Dungeonseeker/linbox-qt5#1]
Hi, @Dungeonseeker 
My virtual env contains all the required python module.

```
sunmin@unmatched:~$ .venv/sunmin/bin/pip list
Package              Version
-------------------- -------
packaging            23.1
pip                  23.0.1
PySide6              6.5.0
pyxdg                0.28
setuptools           66.1.1
shiboken6            6.5.0
shiboken6-generator  6.5.0
show-in-file-manager 1.1.4
wheel                0.40.0
xdgenvpy             2.3.5
```
But, when I launch this application, it complains
```
~/.venv/sunmin/bin/python3.11  linbox.py
Traceback (most recent call last):
  File "/home/sunmin/src/c-86box/linbox-qt5/linbox.py", line 11, in <module>
    from ui.ui_createwindow import Ui_CreateWindow
  File "/home/sunmin/src/c-86box/linbox-qt5/ui/ui_createwindow.py", line 17, in <module>
    import ui.linbox_rc
ModuleNotFoundError: No module named 'ui.linbox_rc'
```
I suspect those files located at **ui/designer_files/** caused this failure

What should I do with those design files,  thanks for your great job!

**Comment by Dungeonseeker** [comment]
Hi, thanks for the report. This seems to be an error on my part, the file it says is missing is the link to the application resources, looks like it didn't recreate the file after my last edit. I'll push an update ASAP to fix this.

**Comment by Dungeonseeker** [comment]
Should be fixed now.

**Comment by sunmin89** [comment]
Hi, @Dungeonseeker 

Thanks for your instant fixing!

It really works, but I came across two more issues.

1.  This app failed to create a directory **~/.config/Linbox**.
2.  I can't create a virtual machine named **hellovm**.

```
Traceback (most recent call last):
  File "/home/sunmin/src/c-86box/linbox-qt5/linbox.py", line 298, in ok
    vmhndlr.create_vm(self.vmname, self.run_method)
                                   ^^^^^^^^^^^^^^^
AttributeError: 'CreateWindow' object has no attribute 'run_method'
Traceback (most recent call last):
  File "/home/sunmin/src/c-86box/linbox-qt5/linbox.py", line 298, in ok
    vmhndlr.create_vm(self.vmname, self.run_method)
                                   ^^^^^^^^^^^^^^^
AttributeError: 'CreateWindow' object has no attribute 'run_method'
[]
hellovm
```
My host info is Debian 12 with xfce running on Riscv64.

I wish you can have a look if it is convenient.

Thanks again.

**Comment by Dungeonseeker** [comment]
> Hi, @Dungeonseeker
> 
> Thanks for your instant fixing!
> 
> It really works, but I came across two more issues.
> 
>     1. This app failed to create a directory **~/.config/Linbox**.
> 
>     2. I can't create a virtual machine named **hellovm**.
> 
> 
> ```
> Traceback (most recent call last):
>   File "/home/sunmin/src/c-86box/linbox-qt5/linbox.py", line 298, in ok
>     vmhndlr.create_vm(self.vmname, self.run_method)
>                                    ^^^^^^^^^^^^^^^
> AttributeError: 'CreateWindow' object has no attribute 'run_method'
> Traceback (most recent call last):
>   File "/home/sunmin/src/c-86box/linbox-qt5/linbox.py", line 298, in ok
>     vmhndlr.create_vm(self.vmname, self.run_method)
>                                    ^^^^^^^^^^^^^^^
> AttributeError: 'CreateWindow' object has no attribute 'run_method'
> []
> hellovm
> ```
> 
> My host info is Debian 12 with xfce running on Riscv64.
> 
> I wish you can have a look if it is convenient.
> 
> Thanks again.

I'm not actually sure I can fix this, my best guess is this is a RiscV issue. both the config creator and the run_method method use the XDG spec to grab your config folder and to check if you have the flatpak version installed respectively.

It might be that XDG doesn't exist on RiscV or maybe XFCE doesn't use it. I'll take a look but it might take a while since I'll have to spin up a VM and try XFCE to check if everything works on X86.

**Comment by Dungeonseeker** [comment]
Sorry but afaict this is a RiscV issue, I've tested Linbox on XFCE on X86 and it works fine as long as QT6, xdg-desktop-portal and xdg-user-dirs is installed. Don't think I can fix this since I have no way of testing on RiscV.
